#!/bin/bash

## Static global with the path ot the subfolder diff-project
CURRENT_FOLDER="./scripts/gitDiffMergeTxt"
DIR="$CURRENT_FOLDER/results"
LOG_PATH="$DIR/log"

SCRIPT_NAME="gitdiff-branches-data"
SCRIPT_PATH="$CURRENT_FOLDER/bash/$SCRIPT_NAME"

GIT_DIFF_BRANCHES='git-diff-branches.log'
GIT_DIFF_BRANCH_PATH="$LOG_PATH/$GIT_DIFF_BRANCHES"

DIFFERENCE='differences.log'
DIFFERENCE_PATH="$LOG_PATH/$DIFFERENCE"

MERGE_FILE='git-diff-merge-file-mod.txt'
MERGE_PATH="$DIR/$MERGE_FILE"

PATH_FIRST_SCRIPT="$CURRENT_FOLDER/bash/gitdiff-with-line"

#Function to check if the line receive as param content the git annotation of differences:
#@@ -
lineContentGitAnnotation() {
  local line=$1

  SUB='@@ -'
  if [[ "$line" == "$SUB"* ]]; then
    return 0
  fi
  return 1
}

#Function to check if the line receive as param content the annotation:
# : ##
lineTeamAnnotationHash() {
  local line=$1
  local numberList='s/[0-9]//g'

  line=$(echo "$line" | sed "$numberList")
  SUB=': ##'
  if [[ "$line" == "$SUB"* ]]; then
    return 0
  fi
  return 1
}

#Function to check if the line receive as param content the annotation:
#+++ b/
lineContentFileName() {
  local line=$1

  SUB='+++ b/'
  if [[ "$line" == "$SUB"* ]]; then
    return 0
  fi
  return 1
}

##Function to check breaking line.
lineEndByHeaderNewLineHash() {
  local line=$1
  local length=${#line}
  SUB=$'\n'"##"
  SUB2=$'\r'"##"

  if [[ "$line" == *"$SUB" || "$line" == *"$SUB2" ]]; then
    return 0
  fi
  return 1
}

#Function to check if the line receive as param content the annotation:
# ##
lineStartByHeaderHash() {
  local line=$1
  local length=${#line}
  SUB='##'

  if [[ $length -eq 2 && "$line" == "$SUB"* ]]; then
    return 0
  fi
  return 1
}

##Function to check if the file is a new file on git.
lineContentGitAnnotationAdd() {
  local line=$1
  SUB='--- /dev/null'
  SUB2='+++ /dev/null'

  if [[ ${#line} -eq 13 ]] && [[ "$line" == "$SUB"* ]]; then
    return 0
  elif [[ ${#line} -eq 13 ]] && [[ "$line" == "$SUB2"* ]]; then
    return 2
  else
    return 1
  fi
}

#Function get the line has changed and add into .diff file.
transferAllFileContent() {
  local -n _fileContent=$1

  local countOfLine=0
  local length=${#_fileContent[@]}

  for ((l = 0; l < "$length"; l++)); do
    local lineChangedData=${_fileContent[l]}
    echo "$lineChangedData" >>"$MERGE_PATH"
    countOfLine=$((countOfLine + 1))
  done

  echo "length: $length end L: $l" >>"$GIT_DIFF_BRANCH_PATH"
}

#Function get the line has changed and add into .diff file.
getModifFromFile() {
  local -n _fileContent=$1
  local line=$2
  local specialChar='s@^[^0-9]*\([0-9]\+\).*@\1@'
  local linePosition=1

  if [[ "$line" != "" ]]; then
    linePosition=$(echo "$line" | sed "$specialChar")
  fi

  local countOfLine=0
  local length=${#_fileContent[@]}
  local firstHash=0

  for ((l = "$linePosition" - 1; l < "$length"; )); do
    local lineChangedData=${_fileContent[l]}

    ## check if we fund '##' 2 to stop the loop 0 to check on the lines above 1 to go to look for a second line with '##'
    if [[ $firstHash -lt 2 ]] && lineStartByHeaderHash "$lineChangedData"; then
      firstHash=$((firstHash + 1))
    fi

    if [[ $firstHash -eq 0 ]]; then
      l=$((l - 1))
    elif [[ $firstHash -eq 2 ]]; then
      break
    else
      ## If firstHash == 1 mean we have found one line with '##' and we add the content between the line of '##'
      echo "$lineChangedData" >>"$MERGE_PATH"
      l=$((l + 1))
    fi
    countOfLine=$((countOfLine + 1))
  done

  echo "linePosition: $((linePosition - 1)) length: $length end L: $l" >>"$GIT_DIFF_BRANCH_PATH"
  ## if the l is equal to the number of line of the file we inform we have finished to read the file.
  if [[ $l -eq $length ]]; then
    return 0
  fi
  return 1
}

##Function to store on log the information what the scripts is doing.
printLineInfo() {
  local args=("$@")

  local linePosition=${args[0]}
  local line=${args[1]}
  local previousLine=${args[2]}
  local endOfFile=false
  local nextLineIsDiff=${args[4]}
  local fileExtractDataPath=${args[5]}

  if [[ ${args[3]} == 0 ]]; then
    endOfFile=true
  fi
  {
    echo -e "\n\n---------------\tPOS [>$linePosition<]"
    echo -e "---------------\tMAIN LINE [[>$line<]]"
    echo -e "---------------\tMAIN LINE LENGTH [[>${#line}<]]"
    echo -e "---------------\tPREVIOUS LINE [[>$previousLine<]]"
    echo -e "---------------\tIS_END_OF_FILE [>$endOfFile<]"
    echo -e "---------------\tNEST_LINE_IS_DIFF [>$nextLineIsDiff<]"
    echo -e "---------------\tFILE_TO_EXTRACT_DATA [>$fileExtractDataPath<]"
  } >>"$GIT_DIFF_BRANCH_PATH"
}

mainLoop() {
  local -n _differencesFileData=$1
  local folderFilesPath=$2

  local countOfLine=0
  local nextLineIsDiff=false
  local fileNameParse=''
  local length=${#_differencesFileData[@]}
  local passOnce=1
  local endOfFile=1
  local fileExtractDataPath=''
  local isNewFile=1
  declare -a fileContent

  ## Read the file differences.log line.
  for ((dl = 0; dl < "$length"; dl++)); do
    line=${_differencesFileData[dl]}
    local previousLine=${_differencesFileData[$((dl - 1))]}
    printLineInfo $((dl + 1)) "$line" "$previousLine" "$endOfFile" "$nextLineIsDiff" "$fileExtractDataPath"

    #____________________________________________________________________________________________________________________#
    ## Analyze the line to thing what is content
    lineContentGitAnnotationAdd "$line" "$previousLine"
    local isGitAnnotationAdd=$?
    local isGitAnnotation=1
    if [[ $isGitAnnotationAdd -eq 1 ]]; then
      lineContentGitAnnotation "$line"
      local isGitAnnotation=$?
    fi

    local isTeamAnnotation=1
    lineContentGitAnnotation "$previousLine"
    local isPrvGitAnnotation=$?
    local isPrvTeamAnnotation=1
    local isContentFileName=1

    if [[ endOfFile -eq 1 ]] && [[ "$isGitAnnotation" == 1 ]]; then
      lineTeamAnnotationHash "$line"
      isTeamAnnotation=$?
    fi
    if [[ endOfFile -eq 1 ]] && [[ "$isPrvGitAnnotation" == 1 ]]; then
      lineTeamAnnotationHash "$previousLine"
      isPrvTeamAnnotation=$?
    fi
    if [[ $passOnce -eq 1 ]] || [[ "$endOfFile" == 0 ]]; then
      lineContentFileName "$line"
      isContentFileName=$?
    fi
    echo -e "--------------\tisGitAnnotation: $isGitAnnotation \tisTeamAnnotation: $isTeamAnnotation \tisPrvGitAnnotation: $isPrvGitAnnotation \tisPrvTeamAnnotation: $isPrvTeamAnnotation \tisContentFileName: $isContentFileName \tisGitAnnotationAdd: $isGitAnnotationAdd isNewFile $isNewFile" >>"$GIT_DIFF_BRANCH_PATH"
    #____________________________________________________________________________________________________________________#

    if [[ $isContentFileName -eq 0 && $isGitAnnotationAdd -eq 1 ]] || [[ $isGitAnnotationAdd -ne 1 && $isNewFile -eq 1 ]]; then
      ## If to get the path of the file to extract
      local fileNameParse
      if [[ $isGitAnnotationAdd -eq 2 ]]; then
        fileNameParse=$previousLine
      else
        fileNameParse=$line
      fi

      filePath="${fileNameParse:6}"
      local folderName=${filePath%/*}
      fileExtractDataPath="$filePath"

      if [[ "$folderName" != "$folderFilesPath" ]]; then
        :
      else
        local branchToExtractFileData=$branchB
        if [[ $isGitAnnotationAdd -eq 2 ]]; then
          branchToExtractFileData=$branchA
        fi

        index=0
        fileContent=()
        while read line || [ -n "$line" ]; do
          if lineEndByHeaderNewLineHash "$line"; then
            IFS=$'\n'$'\r' read -a cutLine <<<"$line"
            fileContent[$index]=${cutLine[0]}
            index=$(("$index" + 1))
            fileContent[$index]=${cutLine[1]}
          else
            fileContent[$index]="$line"
          fi
          index=$(("$index" + 1))
        done < <(git show "$branchToExtractFileData:$filePath")

        endOfFile=1
        passOnce=0
        if [[ $isGitAnnotationAdd -ne 1 ]]; then
          isNewFile=0
        fi
        echo "Parse file: $fileExtractDataPath" >>"$GIT_DIFF_BRANCH_PATH"
        echo "Parse file: $fileExtractDataPath"
      fi
    elif $nextLineIsDiff && [[ $endOfFile -eq 1 ]]; then
      ## File to extract the information from the file changed
      if [[ $isNewFile -eq 0 ]]; then
        transferAllFileContent fileContent
        isNewFile=1
        endOfFile=0
      else
        getModifFromFile fileContent "$line"
        endOfFile=$?
      fi
      nextLineIsDiff=false
    elif [[ $isGitAnnotation -eq 0 || $isNewFile -eq 0 ]] ||
      [[ $dl -ge 0 && $isPrvGitAnnotation -eq 1 && $isTeamAnnotation -eq 0 ]]; then
      nextLineIsDiff=true
    else
      nextLineIsDiff=false
    fi
    countOfLine=$((countOfLine + 1))
  done

}

setFilesDifference() {
  {
    git diff "$branchA" "$branchB" -- "$folderFilesPath" -- '*.txt' | $PATH_FIRST_SCRIPT &>"$DIFFERENCE_PATH"
  } || {
    echo "Error: git diff $branchA $branchB having a issue, please confirm that the branches are correct"
  }
}

#Function read the file from differences.log
executeAlgorithm() {
  setFilesDifference "$branchA" "$branchB" "$folderFilesPath"

  local index=0
  declare -a differencesFileData
  IFS=''
  while read line; do
    differencesFileData[$index]="$line"
    index=$(("$index" + 1))
  done <$DIFFERENCE_PATH

  mainLoop differencesFileData "$folderFilesPath"
}

#Function to create the different main folders
createDiffFolder() {
  local deleteDir
  local createDirFile
  local createLogPath
  if [ -d "$LOG_PATH" ]; then
    rm -rf "$DIR"
    deleteDir="The folder $DIR has been deleted"
  fi

  mkdir -p "$LOG_PATH"
  createLogPath="The folder $LOG_PATH has been created"
  touch "$MERGE_PATH"

  touch $GIT_DIFF_BRANCH_PATH
  {
    echo "$deleteDir"
    echo "$createDirFile"
    echo "$createLogPath"
  } >>"$GIT_DIFF_BRANCH_PATH"
}

help() {
  echo ".$SCRIPT_PATH param1 param2 param3"
  echo "param1: { branch to be compare A }"
  echo "param2: {branch to compare B }"
  echo "param3: { folder where are the file }"
  exit 0
}

welcome() {
  echo -e "Welcome to Git Diff Branches this script will take two branches collect the differences between the to branches."
  echo -e "The script will create 'diff-project' folder and add the information of each modified file into a file extension '.diff.txt'."
  echo -e "run the script with --help to have more information.\n"
}

main() {
  welcome
  if [[ $1 == "--help" ]]; then
    help
  fi

  createDiffFolder
  local branchA=$1
  local branchB=$2
  local folderFilesPath=$3

  pwd

  # asking for the name of the branches to be compared
  if [[ -z "$branchA" ]]; then
    read -rp 'What is the name of the branch A ?: ' branchA
  elif [[ -z "$branchB" ]]; then
    read -rp 'What is the name of the branch B ?: ' branchB
  elif [[ -z "$folderFilesPath" ]]; then
    read -rp 'What is the name of the folder where there is the files ?: ' folderFilesPath
  fi

  echo -e "\tParameter #1 branch A is: $branchA"
  echo -e "\tParameter #2 branch B is: $branchB"
  echo -e "\tParameter #3 the folder is: $folderFilesPath\n"

  {
    echo -e "\tParameter #1 branch A is: $branchA"
    echo -e "\tParameter #2 branch B is: $branchB"
    echo -e "\tParameter #3 folder is: $folderFilesPath\n"
  } >>$GIT_DIFF_BRANCH_PATH

  sleep 1

  if [[ -z "$branchA" || -z "$branchB" || -z "$folderFilesPath" ]]; then
    help
  fi

  executeAlgorithm "$branchA" "$branchB" "$folderFilesPath"
}

main "$1" "$2" "$3"
