//-----------------------------------------------
// Z2X_BATCH_HISSTRUCLIB
//-----------------------------------------------

//------------------
//Exemple de spécifique
//(le niveau 1 reste la société
//update Z2X_BATCH_HISSTRUCLIB SET LIBNIV2 = (SELECT LIBELLE FROM Z2X_BATCH_TRPLTR02 WHERE CODE = CODNIV3) WHERE CODTS = 1 ;
//update Z2X_BATCH_HISSTRUCLIB SET CODNIV2 = CODNIV2 WHERE CODTS = 1;
//update Z2X_BATCH_HISSTRUCLIB SET CODNIV3 = CODNIV4 WHERE CODTS = 1;
//update Z2X_BATCH_HISSTRUCLIB SET CODNIV4 = CODNIV5 WHERE CODTS = 1;
//update Z2X_BATCH_HISSTRUCLIB SET CODNIV5 = CODNIV6 WHERE CODTS = 1;
//update Z2X_BATCH_HISSTRUCLIB SET CODNIV6 = CODNIV7 WHERE CODTS = 1;
//
//update Z2X_BATCH_HISSTRUCLIB SET LIBNIV3 = LIBNIV4 WHERE CODTS = 1;
//update Z2X_BATCH_HISSTRUCLIB SET LIBNIV4 = LIBNIV5 WHERE CODTS = 1;
//update Z2X_BATCH_HISSTRUCLIB SET LIBNIV5 = LIBNIV6 WHERE CODTS = 1;
//update Z2X_BATCH_HISSTRUCLIB SET LIBNIV6 = LIBNIV7 WHERE CODTS = 1;
//On va chercher le libellé des niveau dans les table trpltrxx
//Attention le libellé pour le niveau 3 on va chercher dan trpltr03 au lieu de trpltr02 du fait de la concaténation 
//update Z2X_BATCH_HISSTRUCLIB SET LIBNIV1 = (SELECT RAISSOC FROM Z2X_BATCH_SOCIETE WHERE CODE = CODNIV1);
//update Z2X_BATCH_HISSTRUCLIB SET LIBNIV2 = (SELECT MAX(NOM) FROM Z2X_BATCH_ETAB WHERE CODE = CODNIV2) WHERE CODTS = 2; 
//update Z2X_BATCH_HISSTRUCLIB SET LIBNIV3 = (SELECT LIBELLE FROM Z2X_BATCH_TRPLTR03 WHERE CODE = CODNIV3) WHERE CODTS = 1 ;
//update Z2X_BATCH_HISSTRUCLIB SET LIBNIV4 = (SELECT LIBELLE FROM Z2X_BATCH_TRPLTR04 WHERE CODE = CODNIV4) WHERE CODTS = 1 ;
//update Z2X_BATCH_HISSTRUCLIB SET LIBNIV5 = (SELECT LIBELLE FROM Z2X_BATCH_TRPLTR05 WHERE CODE = CODNIV5) WHERE CODTS = 1 ;
//update Z2X_BATCH_HISSTRUCLIB SET LIBNIV6 = (SELECT LIBELLE FROM Z2X_BATCH_TRPLTR06 WHERE CODE = CODNIV6) WHERE CODTS = 1 ;
//On peut mettre en place une purge de la table STD_STRUC_ARBRE pour tout reconstruire a chaque passage du batch.
//purge de la table STD_STRUC_ARBRE (arbre des entités)
//DELETE from STD_STRUC_ARBRE ;
