TRUNCATE TABLE BATCH_ALIM_ORG;
INSERT INTO BATCH_ALIM_ORG SELECT 'GENERAL', 'EQP', MATRICULE_PERE, MATRICULE FROM Z2X_BATCH_MEMBERS  WHERE MATRICULE_PERE <> '(n)' ;
DELETE BATCH_ALIM_ORG WHERE MATRICPERE = MATRICFILS ;