#!/bin/bash

## Static global with the path ot the subfolder diff-project
LOG_PATH='diff-project/log'
DIR='diff-project'
DIR_FILES='diff-project/files'
#DIF_FILE=$LOG_PATH/"different-files.log"

GIT_DIFF_BRANCHES='git-diff-branches.log'
GIT_DIFF_BRANCH_PATH="$LOG_PATH"/"$GIT_DIFF_BRANCHES"

DIFFERENCE='differences.log'
DIFFERENCE_PATH="$LOG_PATH"/"$DIFFERENCE"

DIFFERENCE_FILES='different-files.log'
DIFFERENCE_FILES_PATH="$LOG_PATH"/"$DIFFERENCE_FILES"

NEW_DELETE_FILES='addDelete-files.log'
NEW_DELETE_FILES_PATH="$LOG_PATH"/"$NEW_DELETE_FILES"

MERGE_FILE='merge-file-diff.txt'
MERGE_PATH="$LOG_PATH"/"$MERGE_FILE"

#Function to check if the line receive as param content the git annotation of differences:
#@@ -
lineContentGitAnnotation() {
  local line=$1

  SUB='@@ -'
  if [[ "$line" == "$SUB"* ]]; then
    return 0
  fi
  return 1
}

#Function to check if the line receive as param content the annotation:
# : ##
lineTeamAnnotationHash() {
  local line=$1
  local numberList='s/[0-9]//g'

  line=$(echo "$line" | sed "$numberList")
  SUB=': ##'
  if [[ "$line" == "$SUB"* ]]; then
    return 0
  fi
  return 1
}

#Function to check if the line receive as param content the annotation:
#+++ b/
lineContentFileName() {
  local line=$1

  SUB='+++ b/'
  if [[ "$line" == "$SUB"* ]]; then
    return 0
  fi
  return 1
}

#Function to check if the line receive as param content the annotation:
# ##
lineStartByHeaderHash() {
  local line=$1
  SUB='##'
  if [[ ${#line} == 2 ]] && [[ "$line" == "$SUB"* ]]; then
    return 0
  fi
  return 1
}

#Function browser a map which content all the information of the file to be compare
getArrayFileInfo() {
  local num=$4
  local fileName=$3
  local response=''
  local COUNT=${#filesList[@]}

  for ((i = 0; i < "$COUNT"; i++)); do
    IFS="|" read -r -a arr <<<"${filesList[i]}"
    if [[ ${arr[0]} = "$fileName" ]]; then
      response="${arr[num]}"
      break
    fi
  done
  echo "$response"
}

#Function get the line has changed and add into .diff file
getModifFromFile() {
  local specialChar='s@^[^0-9]*\([0-9]\+\).*@\1@'
  local linePosition=$(echo "$line" | sed "$specialChar")
  local index=0
  declare -a fileChangedData

  echo "LINE => $line"

  IFS=''
  while read lineChangeData; do
    fileChangedData[$index]="$lineChangeData"
    index=$(("$index" + 1))
  done <"$fileExtractDataPath"

  local countOfLine=0
  local length=${#fileChangedData[@]}
  local firstHash=0
  local endPosition=0

  for ((l = "$linePosition" - 1; l < "$length"; )); do
    local lineChangedData=${fileChangedData[l]}

    if (("$firstHash" < 2)) && lineStartByHeaderHash "$lineChangedData"; then
      firstHash=$((firstHash + 1))
    fi

    if (("$firstHash" == 0)); then
      l=$((l - 1))
    elif (("$firstHash" == 2)); then
      endPosition=$((l))
      break
    else
      echo "$lineChangedData" >>"$diffFilePath"
      echo "$lineChangedData" >>"$MERGE_PATH"
      l=$((l + 1))
    fi
    countOfLine=$((countOfLine + 1))
    endPosition=$((l))
  done
  if (("$endPosition" == "$length")); then
    return 0
  else
    return 1
  fi
}

#Function which will browse /log/differences.log and extract the  information
executeAlgorithm2() {
  local index=0
  declare -a differencesFileData

  IFS=''
  while read line; do
    differencesFileData[$index]="$line"
    index=$(("$index" + 1))
  done <$DIFFERENCE_PATH

  local countOfLine=0
  local nextLineIsDiff=false
  local fileNameParse=''
  local length=${#differencesFileData[@]}
  local diffFilePosName=3
  local FileExtractDatPos=1
  local passOnce=1
  local endOfFile=1

  fileExtractDataPath=''
  for ((dl = 0; dl < "$length"; dl++)); do
    line=${differencesFileData[dl]}
    local previousLine=${differencesFileData[$((dl - 1))]}
    {
      echo -e "\n\n---------------\tPOS [ $((dl + 1)) ]"
      echo -e "---------------\tMAIN LINE [[ $line ]]"
      echo -e "---------------\tPREVIOUS LINE [[ $previousLine ]]"
      echo -e "---------------\tIS_END_OF_FILE [ $endOfFile ]"
      echo -e "---------------\tNEST_LINE_IS_DIFF [ $nextLineIsDiff ]"
      echo -e "---------------\tFILE_TO_EXTRACT_DATA [ $fileExtractDataPath ]"
    } >>$GIT_DIFF_BRANCH_PATH

    local isGitAnnotation=1
    local isTeamAnnotation=1
    local isPrvGitAnnotation=1
    local isPrvTeamAnnotation=1
    local isContentFileName=1

    lineContentGitAnnotation "$line"
    isGitAnnotation=$?
    if (("$isGitAnnotation" == 1)); then
      lineTeamAnnotationHash "$line"
      isTeamAnnotation=$?
    fi

    lineContentGitAnnotation "$previousLine"
    isPrvGitAnnotation=$?
    if (("$isPrvGitAnnotation" == 1)); then
      lineTeamAnnotationHash "$previousLine"
      isPrvTeamAnnotation=$?
    fi

    if ( (("$passOnce" == 1)) || (("$endOfFile" == 0))); then
      lineContentFileName "$line"
      isContentFileName=$?
    fi

    echo -e "--------------\tisGitAnnotation: $isGitAnnotation \tisTeamAnnotation: $isTeamAnnotation \tisPrvGitAnnotation: $isPrvGitAnnotation \tisPrvTeamAnnotation: $isPrvTeamAnnotation \tisContentFileName: $isContentFileName" >>$GIT_DIFF_BRANCH_PATH
    if (("$isContentFileName" == 0)); then
      echo "I PASS HERE"
      local fileNameParse=$previousLine
      fileName="$(basename -- "$fileNameParse")"
      diffFilePath=$(getArrayFileInfo "${filesList[@]}" "$fileName" "$diffFilePosName")
      fileExtractDataPath=$(getArrayFileInfo "${filesList[@]}" "$fileName" "$FileExtractDatPos")
      echo "fileName > $fileName"
      echo "fileName > $diffFilePosName"
      echo "diffFilePath > $diffFilePath"
      echo "fileExtractDataPath > $fileExtractDataPath"
      {
        echo -e "--------------\tdiffFilePath: " "$diffFilePath"
        echo -e "--------------\tfileExtractDataPath: " "$fileExtractDataPath"
      } >>$GIT_DIFF_BRANCH_PATH
      endOfFile=1
      passOnce=0
    elif $nextLineIsDiff && (("$endOfFile" == 1)); then
      getModifFromFile
      endOfFile=$?
      nextLineIsDiff=false
    elif (("$isGitAnnotation" == 0)) ||
      ( (("$dl" > 0)) && (("$isPrvGitAnnotation" == 1)) && (("$isTeamAnnotation" == 0))); then
      nextLineIsDiff=true
    else
      nextLineIsDiff=false
    fi

    read -p 'goOn ?: ' goOn
    countOfLine=$((countOfLine + 1))
  done
  echo -e "END OF EXTRACTOR\n" >>$GIT_DIFF_BRANCH_PATH
}

displayArray() {
  local arrayInfo=("$@")
  local length=${#arrayInfo[@]}

  for ((counter = 0; counter < "$length"; counter++)); do
    printf 'ARRAY[%d] %s\n' "$counter" "${arrayInfo[counter]}"
  done
  printf "\n"
}

getAddFilesArray() {
  addFilesString=$(git diff --name-only --diff-filter=AD "$branchA" "$branchB" -- "$folderFilesPath" | tr "\n" " ")
  echo "$addFilesString"
}

getModifFilesArray() {
  modFilesString=$(git diff --name-only "$branchA" "$branchB" -- "$folderFilesPath" | tr "\n" " ")
  echo "$modFilesString"
}

printLineInfo() {
  local args=("$@")

  displayArray "${args[@]}"
  local linePosition=${args[0]}
  local line=${args[1]}
  local previousLine=${args[2]}
  local endOfFile=false
  local nextLineIsDiff=${args[4]}
  local fileExtractDataPath=${args[5]}

    if [[ ${args[3]} == 0 ]]; then
      endOfFile=true
    fi
  {
    echo -e "\n\n---------------\tPOS [ $linePosition ]"
    echo -e "---------------\tMAIN LINE [[ $line ]]"
    echo -e "---------------\tPREVIOUS LINE [[ $previousLine ]]"
    echo -e "---------------\tIS_END_OF_FILE [ $endOfFile  ]"
    echo -e "---------------\tNEST_LINE_IS_DIFF [ $nextLineIsDiff ]"
    echo -e "---------------\tFILE_TO_EXTRACT_DATA [ $fileExtractDataPath ]"
  }
  #    } >>"$GIT_DIFF_BRANCH_PATH"
}

mainLoop() {
  local -n _addFilesArray=$1
  local -n _modFilesArray=$2
  local -n _differencesFileData=$3

  local countOfLine=0
  local nextLineIsDiff=false
  local fileNameParse=''
  local length=${#differencesFileData[@]}
  local diffFilePosName=3
  local FileExtractDatPos=1
  local passOnce=1
  local endOfFile=1
  local fileExtractDataPath=''

  for ((dl = 0; dl < "$length"; dl++)); do
    line=${differencesFileData[dl]}
    local previousLine=${differencesFileData[$((dl - 1))]}
    printLineInfo $((dl + 1)) "$line" "$previousLine" "$endOfFile" "$nextLineIsDiff" "$fileExtractDataPath"

    #____________________________________________________________________________________________________________________#
    lineContentGitAnnotation "$line"
    local isGitAnnotation=$?
    local isTeamAnnotation=1
    lineContentGitAnnotation "$previousLine"
    local isPrvGitAnnotation=$?
    local isPrvTeamAnnotation=1
    local isContentFileName=1

    if (("$isGitAnnotation" == 1)); then
      lineTeamAnnotationHash "$line"
      isTeamAnnotation=$?
    fi
    if (("$isPrvGitAnnotation" == 1)); then
      lineTeamAnnotationHash "$previousLine"
      isPrvTeamAnnotation=$?
    fi
    if ( (("$passOnce" == 1)) || (("$endOfFile" == 0))); then
      lineContentFileName "$line"
      isContentFileName=$?
    fi
    echo -e "--------------\tisGitAnnotation: $isGitAnnotation \tisTeamAnnotation: $isTeamAnnotation \tisPrvGitAnnotation: $isPrvGitAnnotation \tisPrvTeamAnnotation: $isPrvTeamAnnotation \tisContentFileName: $isContentFileName" >>$GIT_DIFF_BRANCH_PATH
    #____________________________________________________________________________________________________________________#

    if (("$isContentFileName" == 0)); then
      echo "I PASS HERE"
      local fileNameParse=$line
      fileName="$(basename -- "$fileNameParse")"
      filePath="${fileNameParse:6}"
      echo "fileNameParse => '$fileNameParse'"
      echo "fileName => $fileName"
      echo "filePath => $filePath"

      #HERE MAKE A GIT SHOW TO GET THE INFORMATION FROM THE FILE

      endOfFile=1
      passOnce=0
    fi

    countOfLine=$((countOfLine + 1))
    read -p 'goOn ?: ' goOn
  done

}

executeAlgorithm() {
  setFilesDifference "$branchA" "$branchB" "$folderFilesPath"

  declare -a addFilesArray=($(getAddFilesArray))
  declare -a modFilesArray=($(getModifFilesArray))

  local index=0
  declare -a differencesFileData
  IFS=''
  while read line; do
    differencesFileData[$index]="$line"
    index=$(("$index" + 1))
  done <$DIFFERENCE_PATH

  mainLoop addFilesArray modFilesArray differencesFileData
}

setFilesDifference() {
  {
    git diff "$branchA" "$branchB" -- "$folderFilesPath" | ./scripts/gitdiff-with-line >"$DIFFERENCE_PATH"
  } || {
    echo "Error: git diff $branchA $branchB having a issue, please confirm that the branches are correct"
  }
}

#Function to create the different main folders
createDiffFolder() {
  local deleteDir
  local createDirFile
  local createLogPath
  if [ -d "$LOG_PATH" ]; then
    rm -rf "$DIR"
    deleteDir="The folder $DIR has been deleted"
  fi

  mkdir -p "$DIR_FILES"
  createDirFile="The folder $DIR_FILES has been created"
  mkdir -p "$LOG_PATH"
  createLogPath="The folder $LOG_PATH has been created"
  touch "$MERGE_PATH"

  touch $GIT_DIFF_BRANCH_PATH
  {
    echo "$deleteDir"
    echo "$createDirFile"
    echo "$createLogPath"
  } >>"$GIT_DIFF_BRANCH_PATH"
}

help() {
  echo ./gitdiff-branch-data '{ branch to be compare A }' '{branch to compareB}'
  exit 0
}

welcome() {
  echo -e "Welcome to Git Diff Branches this script will take two branches collect the differences between the to branches."
  echo -e "The script will create 'diff-project' folder and add the information of each modified file into a file extension '.diff.txt'.\n"
}

main() {
  welcome
  createDiffFolder
  local branchA=$1
  local branchB=$2
  local folderFilesPath=$3

  if [[ $1 == "--help" ]]; then
    help
  fi

  # asking for the name of the branches to be compared
  if [[ -z "$branchA" ]]; then
    read -rp 'What is the name of the branch A ?: ' branchA
  elif [[ -z "$branchB" ]]; then
    read -rp 'What is the name of the branch B ?: ' branchB
  elif [[ -z "$folderFilesPath" ]]; then
    read -rp 'What is the name of the folder where there is the files ?: ' folderFilesPath
  fi

  echo "Parameter #1 is $branchA"
  echo "Parameter #2 is $branchB"
  echo "Parameter #3 is $folderFilesPath"

  {
    echo "Parameter #1 is $branchA"
    echo "Parameter #2 is $branchB"
    echo "Parameter #3 is $folderFilesPath"
  } >>$GIT_DIFF_BRANCH_PATH

  sleep 1

  if [[ -z "$branchA" || -z "$branchB" || -z "$folderFilesPath" ]]; then
    help
  fi

  executeAlgorithm "$branchA" "$branchB" "$folderFilesPath"
}

main "$1" "$2" "$3"
