OPTIONS (DIRECT=TRUE,PARALLEL=TRUE,ERRORS=500)
UNRECOVERABLE
LOAD DATA
INFILE 'FILE_FROM_CMD_LINE' "str X'A10D0A'"
APPEND
INTO TABLE BDC_BULLETIN_TMP
(
MATRIC POSITION(1:7) CHAR
,RUPED POSITION(8:11) INTEGER EXTERNAL
,NUMPAGE POSITION(12:13) INTEGER EXTERNAL
,BULLETIN POSITION(*) CHAR(16000) TERMINATED BY X'A1'
)