DELETE FROM ETAT_CIV WHERE MATRIC NOT IN (SELECT MATRIC FROM SECUMATRIC);
UPDATE ETAT_CIV SET (EMAIL,ET_TEL_PRO_FIXE,ET_TEL_PRO_PORT,ET_FAX_PRO,ET_EMAIL_PERSO) = ( SELECT EMAIL,NOPRO,NOPORT,NOFAX,MELPER FROM GA_TMP_EMAIL WHERE GA_TMP_EMAIL.MATRIC=ETAT_CIV.MATRIC );
INSERT INTO GTA_JOU_EMPLOYE SELECT MATRIC,NVL(NOM,' '),NVL(PRENOM,' '),SYSDATE FROM SECUMATRIC WHERE MATRIC NOT IN (SELECT ID FROM GTA_JOU_EMPLOYE);
UPDATE GA_ACCTRAV SET DSACC=99999999-DSACC, DSDAR=99999999-DSDAR;
